# Generated by Django 3.2.5 on 2022-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danismma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=24)),
                ('mail', models.EmailField(max_length=254)),
                ('metin', models.CharField(max_length=10000)),
            ],
        ),
    ]
