# Generated by Django 3.2.5 on 2022-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danisma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Danismma',
            new_name='Danisma',
        ),
    ]
