# Generated by Django 3.2.5 on 2022-03-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kayit',
        ),
    ]
